### ISSUE TITLE
Recurrent connections on nodes aren't displayed

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-gui#443]
```
import nengo
model = nengo.Network()
with model:
    stim = nengo.Node(size_in=1)
    a = nengo.Ensemble(n_neurons=50, dimensions=1)
    nengo.Connection(stim, a)
    nengo.Connection(stim, stim)  # not displayed
    nengo.Connection(a, a)
```

**Comment by tcstewar** [comment]
Oops.

When fixing this, it'd also be nice to show recurrent connections on collapsed Networks as well....

**Comment by krisfrenette** [comment]
Closing this out as it is fixed.

**Comment by tcstewar** [comment]
Is this fixed?  It doesn't look like it to me.   Note that this is about a recurrent connection on a Node, not on an Ensemble.  So something like this:

```python
import nengo

model = nengo.Network()
with model:

    b = nengo.Node(lambda t, x: x, size_in=1, size_out=1)
    nengo.Connection(b, b)
```

**Comment by krisfrenette** [comment]
No problem. I will verify and reopen. I based my response on the example
given by Aaron.

**Comment by tcstewar** [comment]
> No problem. I will verify and reopen. I based my response on the example given by Aaron.

Sounds good!  Aaron's example also still doesn't show three Connections for me.  (stim->a is shown, and a->a is shown, but stim->stim is not shown)

**Comment by krisfrenette** [comment]
Yeah, I missed that. Reopening as this is still present
